In [1]:
import numpy as np
row,col = input("Enter rowXcol : ").split('X')
row,col = int(row),int(col)
row,col

Enter rowXcol : 4X3


(4, 3)

In [2]:
print("Enter Values (Column wise) : ")
Y = np.array([[float(input()) for j in range(col)] for i in range(row)])
print(Y,Y.shape)

Enter Values (Column wise) : 
1
1
2
1
2
0
-1
-3
-1
-1
-2
-3
[[ 1.  1.  2.]
 [ 1.  2.  0.]
 [-1. -3. -1.]
 [-1. -2. -3.]] (4, 3)


In [20]:
a = np.array([float(input())for i in range(col)])
print(a,a.shape)

1
1
1
[1. 1. 1.] (3,)


In [21]:
choice = int(input("1.same\n2.different\n"))
if choice == 1 :
    b = float(input("Enter b = "))
    B = np.array([b for i in range(row)])
else :
    B = np.array([float(input()) for i in range(row)])
print(B,B.shape)

1.same
2.different
1
Enter b = 0.5
[0.5 0.5 0.5 0.5] (4,)


In [5]:
bmin = float(input("bmin = "))
nk = float(input("n(k) = "))
print(bmin,nk)

bmin = 0.05
n(k) = 0.5
0.05 0.5


In [25]:
k = int(input("Maximum iteration : "))
index = 0
while index < k :
    e = np.dot(Y,a) - B
    ep = np.divide(e + np.abs(e),2)
    B = B + np.multiply(np.transpose(e),2*nk)
    a = np.dot(np.transpose(Y),b)
    B = np.subtract(B,0.1)
    index += 1
    nk = (1/index)
    print(np.abs(e))
    if np.abs(e).any() < bmin :
        print(a,B)
        break
#print(a,"\n\n",B)
#else :
#    print("No solution found")

Maximum iteration : 10
[[1.66666667e+00 2.24180190e+09 2.01762171e+10 2.24180190e+10]
 [2.24180190e+09 1.66666667e+00 1.79344152e+10 2.01762171e+10]
 [2.01762171e+10 1.79344152e+10 1.66666667e+00 2.24180190e+09]
 [2.24180190e+10 2.01762171e+10 2.24180190e+09 1.66666667e+00]]
[[1.70000000e+00 2.33147398e+09 2.09832658e+10 2.33147398e+10]
 [2.33147397e+09 1.70000000e+00 1.86517918e+10 2.09832658e+10]
 [2.09832658e+10 1.86517918e+10 1.70000000e+00 2.33147398e+09]
 [2.33147398e+10 2.09832658e+10 2.33147397e+09 1.70000000e+00]]
[[1.60000000e+00 6.99442193e+09 6.29497974e+10 6.99442193e+10]
 [6.99442193e+09 1.60000000e+00 5.59553754e+10 6.29497974e+10]
 [6.29497974e+10 5.59553754e+10 1.60000000e+00 6.99442193e+09]
 [6.99442193e+10 6.29497974e+10 6.99442193e+09 1.60000000e+00]]
[[1.00000000e-01 1.39888439e+10 1.25899595e+11 1.39888439e+11]
 [1.39888439e+10 1.00000000e-01 1.11910751e+11 1.25899595e+11]
 [1.25899595e+11 1.11910751e+11 1.00000000e-01 1.39888439e+10]
 [1.39888439e+11 1.25899595e+