In [36]:
import numpy as np
row,col = input("Enter rowXcol : ").split('X')
row,col = int(row),int(col)

Enter rowXcol : 4X3


In [37]:
row,col

(4, 3)

In [38]:
print("Enter Values (Column wise) : ")
Y = np.array([[float(input()) for j in range(col)] for i in range(row)])

Enter Values (Column wise) : 
1
1
2
1
2
0
-1
-3
-1
-1
-2
-3


In [39]:
Y

array([[ 1.,  1.,  2.],
       [ 1.,  2.,  0.],
       [-1., -3., -1.],
       [-1., -2., -3.]])

In [40]:
Yt = np.transpose(Y)
Yt

array([[ 1.,  1., -1., -1.],
       [ 1.,  2., -3., -2.],
       [ 2.,  0., -1., -3.]])

In [41]:
YtY = np.dot(Yt,Y)
YtY

array([[ 4.,  8.,  6.],
       [ 8., 18., 11.],
       [ 6., 11., 14.]])

In [53]:
r,c = YtY.shape
YtYinv = []
if r == c :
    YtYinv = np.matrix.round(np.linalg.inv(YtY),4)
else :
    YtYinv = np.matrix.round(np.linalg.pinv(YtY),4)
YtYinv

array([[ 3.6389, -1.2778, -0.5556],
       [-1.2778,  0.5556,  0.1111],
       [-0.5556,  0.1111,  0.2222]])

In [54]:
Yp = np.matrix.round(np.dot(YtYinv,Yt),4)
Yp

array([[ 1.2499e+00,  1.0833e+00,  7.5010e-01,  5.8350e-01],
       [-5.0000e-01, -1.6660e-01, -5.0010e-01, -1.6670e-01],
       [-1.0000e-04, -3.3340e-01,  1.0000e-04, -3.3320e-01]])

In [55]:
choice = int(input("1.same\n2.different\n"))
if choice == 1 :
    b = float(input("Enter b = "))
    B = np.array([b for i in range(row)])
else :
    B = np.array([float(input()) for i in range(row)])
print(B,B.shape)

1.same
2.different1
Enter b = 0.5
[0.5 0.5 0.5 0.5] (4,)


In [56]:
a = np.dot(Yp,B)
print(a,a.shape)

[ 1.8334 -0.6667 -0.3333] (3,)


In [57]:
error = np.dot(Y,a) - B
error

array([ 1.00000000e-04,  0.00000000e+00, -1.66533454e-16, -1.00000000e-04])

In [58]:
eAmpli = np.dot(np.transpose(error),error)
eAmpli

2.0000000000017798e-08