In [1]:
import numpy as np

In [2]:
features = int(input("Enter number of features : "))
dataPoints = int(input("Enter number of data points : "))

Enter number of features : 2
Enter number of data points : 4


In [6]:
print("Enter dataset")
dataSet = np.array([[float(input()) for i in range(features)] for i in range(dataPoints)])

Enter dataset
2
2.1
3
3.4
4
3.9
6
5.8


In [7]:
print(dataSet)

[[2.  2.1]
 [3.  3.4]
 [4.  3.9]
 [6.  5.8]]


In [69]:
m = [0 for i in range(features)]
for i in dataSet :
    index = 0
    for j in i :
        m[index] += j
        index += 1
m = np.divide(np.array(m),dataPoints).reshape([features,1])
print(m)

[[3.75]
 [3.8 ]]


In [82]:
ScatterMatrix = []
for i in dataSet :
    x = i.reshape([features,1]) - m
    ScatterMatrix.append(np.dot(x,x.transpose()))
S = np.zeros_like(ScatterMatrix[0])
for i in ScatterMatrix :
    S += i
print(S)

[[8.75 7.8 ]
 [7.8  7.06]]


In [101]:
#Eigen Values and vector
values,vectors = np.linalg.eig(S)
print("Eigen Values :\n",values,"\n\nEigen Vectors :\n",vectors)
#print(np.linalg.eigvals(S))

Eigen Values :
 [15.75063732  0.05936268] 

Eigen Vectors :
 [[ 0.74421206 -0.66794342]
 [ 0.66794342  0.74421206]]


In [102]:
#Here taking eigen vector as in the class
e = np.array([1.11,1])
e

array([1.11, 1.  ])

In [103]:
P = []
for i in dataSet :
    P.append(np.dot(e.transpose(),i))
index = 1
for i in P :
    print("p{:} = {:}".format(index,i),end="\n")
    index+=1

p1 = 4.32
p2 = 6.73
p3 = 8.34
p4 = 12.46
