In [3]:
import numpy as np

## Geting size of input and output

In [2]:
Number_of_Samples,Length_of_Sample,Length_of_Output = int(input("Enter number of samples ")),int(input("Enter length of samples ")),int(input("Enter length output "))

Enter number of samples 4
Enter length of samples 4
Enter length output 2


## Taking input and output and printing it

In [7]:
Input = np.zeros((Number_of_Samples,Length_of_Sample))
Output = np.zeros((Number_of_Samples,Length_of_Output))

In [8]:
Input

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
Input.shape

(4, 4)

In [10]:
Output

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
Output.shape

(4, 2)

In [19]:
print("Enter input (Row wise separated by space)")
for i in range(Number_of_Samples) :
    x = [input().split(' ')]
    for j in range(Length_of_Sample) :
        Input[i,j] = x[0][j]

Enter input (Row wise separated by space)
1 0 1 0
1 0 0 1
1 1 0 0
0 0 1 1


In [20]:
Input

array([[1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.]])

In [21]:
print("Enter output(Row wise separated by space)")
for i in range (Number_of_Samples) :
    x = [input().split(' ')]
    for j in range(Length_of_Output) :
        Output[i,j] = x[0][j]

Enter output(Row wise separated by space)
1 0
1 0
0 1
0 1


In [22]:
Output

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.]])

## Initializing Weight Matrix to 0 and procees to get the final weight matrix

In [51]:
Weight = np.zeros((Number_of_Samples,Length_of_Output))
index = 0

In [24]:
Weight

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
Weight.shape

(4, 2)

#### *Run it only once, after that rerun weight initialization otherwise Weight is keep getting updated 

In [55]:
if not index :
    for In,Out in zip(Input,Output) :
        for k in range(Length_of_Output) :
            for j in range(Number_of_Samples) :
                Weight[j,k] += In[j]*Out[k]
        index += 1
        print("Afte processing",index,"\n",Weight,"\n")
else :
    print(Weight)

[[2. 1.]
 [0. 1.]
 [1. 1.]
 [1. 1.]]
