In [1]:
import numpy as np

## Input

In [106]:
Number_of_Samples = int(input("Enter number of samples "))
Length_of_Samples = int(input("Enter the length of the sample "))
Number_of_Cluster = int(input("Enter number of clusters "))

Enter number of samples 4
Enter the length of the sample 4
Enter number of clusters 2


In [107]:
X = np.zeros((Number_of_Samples,Length_of_Samples))
X

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [108]:
X.shape

(4, 4)

In [109]:
print("Enter input column wise")
for i in range(Number_of_Samples) :
    x = [input().split(' ')]
    for j in range(Length_of_Samples) :
        X[i,j] = x[0][j]
print(X)

Enter input column wise
0 0 1 1
1 0 0 0
0 1 1 0
0 0 0 1
[[0. 0. 1. 1.]
 [1. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 1.]]


In [110]:
Learning_rate = float(input("Enter learning rate "))
Learning_rate

Enter learning rate 0.5


0.5

## Declare and initialize Weight Metrix

In [111]:
Weight = None

In [112]:
Choice = int(input("1.Random\n2.Specific\n\nChoice ")) 
if  Choice == 2 :
    Weight = np.zeros((Length_of_Samples,Number_of_Cluster))
    print("Enter values column wise")
    for i in range(Length_of_Samples) :
        x = [input().split(' ')]
        for j in range(Number_of_Cluster) :
            Weight[i,j] = x[0][j]
else :
    Weight = np.random.rand(Length_of_Samples,Number_of_Cluster)

1.Random
2.Specific

Choice 2
Enter values column wise
.2 .9
.4 .7
.6 .5
.8 .3


In [113]:
Weight

array([[0.2, 0.9],
       [0.4, 0.7],
       [0.6, 0.5],
       [0.8, 0.3]])

In [114]:
Weight = Weight.T

In [115]:
Weight

array([[0.2, 0.4, 0.6, 0.8],
       [0.9, 0.7, 0.5, 0.3]])

In [116]:
Distance = np.zeros(Number_of_Cluster)

In [117]:
Distance

array([0., 0.])

In [118]:
Distance.shape

(2,)

In [119]:
for x in X :
    index = 0
    for weight in Weight :
        Sum= 0
        for i,j in zip(x,weight) :
            Sum += (i-j)**2
        Distance[index] = round(Sum,4)
        index += 1
    print("Distance :",Distance,end="\n")
    j = np.where(Distance==(min(Distance)))[0][0]
    for i in range(Length_of_Samples) :
        Weight[j,i] = Weight[j,i] + Learning_rate * (x[i] - Weight[j,i])
    print("Weight Matrix :\n",Weight.T,end="\n\n")
    for i in range(len(Distance)) :
        Distance[i] = 0

Distance : [0.4  2.04]
Weight Matrix :
 [[0.1 0.9]
 [0.2 0.7]
 [0.8 0.5]
 [0.9 0.3]]

Distance : [2.3  0.84]
Weight Matrix :
 [[0.1  0.95]
 [0.2  0.35]
 [0.8  0.25]
 [0.9  0.15]]

Distance : [1.5  1.91]
Weight Matrix :
 [[0.05 0.95]
 [0.6  0.35]
 [0.9  0.25]
 [0.45 0.15]]

Distance : [1.475 1.81 ]
Weight Matrix :
 [[0.025 0.95 ]
 [0.3   0.35 ]
 [0.45  0.25 ]
 [0.725 0.15 ]]



In [120]:
Weight.T

array([[0.025, 0.95 ],
       [0.3  , 0.35 ],
       [0.45 , 0.25 ],
       [0.725, 0.15 ]])